server:
  port: 9981

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.76.51.38:9901/eureka/

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: service-export
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/