server:
  port: 9981

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.76.51.38:9901/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

foo: 123

spring:
  application:
    name: service-export
  cloud:
    config:
      label: master
      profile: dev
      uri: http://10.76.51.38:9921/