foo: 123

spring:
  application:
    name: export-server
  cloud:
    loadbalancer:
      retry:
        enabled: false

server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#feign:
#  hystrix:
#    enabled: false
#  compression:
#    request:
#      enabled: true
#      min-type: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enable: true

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info




ribbon:
  ReadTimeout: 9000 #请求处理的超时时间
  ConnectTimeout: 3000 #请求连接的超时时间
# MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
